### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mmarkell**

### CODE REVIEW

**Comment by verkaufer** [comment]
Thanks for catching this! Appreciate the contribution. Approved.

**Review by verkaufer — APPROVED** [review]

**Comment by mmarkell** [comment]
For sure! What exactly do I need to change there?

**Comment by verkaufer** [comment]
> For sure! What exactly do I need to change there?

A quick line about updating the README under the `Latest -> Fixes` header would be great! I'll merge once that's done.

**Comment by mmarkell** [comment]
@verkaufer Great, done

**Review by verkaufer — APPROVED** [review]

**Pull request merged**
